// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7JZkOVO82ShDEUAEy9wSLORuzjNrBWwY',
    appId: '1:106873785957:web:2527472c79e28c0186408c',
    messagingSenderId: '106873785957',
    projectId: 'salesrecords-93168',
    authDomain: 'salesrecords-93168.firebaseapp.com',
    storageBucket: 'salesrecords-93168.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOZ_0JKPgEdPDvzjPIGbNE2n7FU24U08o',
    appId: '1:106873785957:android:d16900a94b535ff886408c',
    messagingSenderId: '106873785957',
    projectId: 'salesrecords-93168',
    storageBucket: 'salesrecords-93168.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5fuIwbQ7uv0ScCXI4GcZnfOdgWyV8n1I',
    appId: '1:106873785957:ios:4331a949ba94594086408c',
    messagingSenderId: '106873785957',
    projectId: 'salesrecords-93168',
    storageBucket: 'salesrecords-93168.appspot.com',
    iosClientId: '106873785957-3u068bc2jkuimib0s4ui3u94ki6jmm82.apps.googleusercontent.com',
    iosBundleId: 'com.example.salesRecordsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5fuIwbQ7uv0ScCXI4GcZnfOdgWyV8n1I',
    appId: '1:106873785957:ios:4331a949ba94594086408c',
    messagingSenderId: '106873785957',
    projectId: 'salesrecords-93168',
    storageBucket: 'salesrecords-93168.appspot.com',
    iosClientId: '106873785957-3u068bc2jkuimib0s4ui3u94ki6jmm82.apps.googleusercontent.com',
    iosBundleId: 'com.example.salesRecordsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7JZkOVO82ShDEUAEy9wSLORuzjNrBWwY',
    appId: '1:106873785957:web:ed4b926f634b8ea786408c',
    messagingSenderId: '106873785957',
    projectId: 'salesrecords-93168',
    authDomain: 'salesrecords-93168.firebaseapp.com',
    storageBucket: 'salesrecords-93168.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyB7JZkOVO82ShDEUAEy9wSLORuzjNrBWwY',
    appId: '1:106873785957:web:4fc585520aff6e0f86408c',
    messagingSenderId: '106873785957',
    projectId: 'salesrecords-93168',
    authDomain: 'salesrecords-93168.firebaseapp.com',
    storageBucket: 'salesrecords-93168.appspot.com',
  );
}
